swagger: '2.0'
info:
  version: "1.0.0"
  title: Ecommerce API
  description: A simple ecommerce API built with Flask and MySQL.
  contact:
    name: API Support
    url: "http://www.example.com/support"
    email: "support@example.com"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"

# Security Definitions
securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Enter 'Bearer' [space] and then your token in the text input below. Example: 'Bearer abcde12345'"

security:
  - Bearer: []

paths:
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: "Register a new user"
      description: "Register a new user by providing a username, email, and password."
      parameters:
        - in: "body"
          name: "body"
          description: "User registration details"
          required: true
          schema:
            type: "object"
            required:
              - username
              - email
              - password
            properties:
              username:
                type: "string"
              email:
                type: "string"
              password:
                type: "string"
      responses:
        201:
          description: "User created successfully"
        400:
          description: "User already exists or invalid input"

  /auth/login:
    post:
      tags:
        - "Auth"
      summary: "Login a user"
      description: "Authenticate a user by providing email and password."
      parameters:
        - in: "body"
          name: "body"
          description: "User login details"
          required: true
          schema:
            type: "object"
            required:
              - email
              - password
            properties:
              email:
                type: "string"
              password:
                type: "string"
      responses:
        200:
          description: "User logged in successfully"
        401:
          description: "Invalid credentials"

  /products/:
    get:
      tags:
        - "Product"
      summary: "Retrieve all products"
      description: "Get a list of all products in the inventory."
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "A list of products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"

    post:
      tags:
        - "Product"
      summary: "Create a new product"
      description: "Add a new product to the inventory."
      parameters:
        - in: "body"
          name: "body"
          description: "Product details"
          required: true
          schema:
            $ref: "#/definitions/Product"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        201:
          description: "Product created successfully"
        400:
          description: "Invalid input"

  /products/{product_id}:
    get:
      tags:
        - "Product"
      summary: "Get product details"
      description: "Retrieve details of a product by its ID."
      parameters:
        - in: "path"
          name: "product_id"
          required: true
          type: "integer"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Product details"
          schema:
            $ref: "#/definitions/Product"
        404:
          description: "Product not found"

    put:
      tags:
        - "Product"
      summary: "Update a product"
      description: "Update details of an existing product by its ID."
      parameters:
        - in: "path"
          name: "product_id"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Updated product details"
          required: true
          schema:
            $ref: "#/definitions/Product"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Product updated successfully"
        404:
          description: "Product not found"

    delete:
      tags:
        - "Product"
      summary: "Delete a product"
      description: "Delete a product by its ID."
      parameters:
        - in: "path"
          name: "product_id"
          required: true
          type: "integer"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Product deleted successfully"
        404:
          description: "Product not found"

  /orders/:
    get:
      tags:
        - "Order"
      summary: "Retrieve all orders"
      description: "Get a list of all orders placed by the authenticated user."
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "A list of orders"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Order"

    post:
      tags:
        - "Order"
      summary: "Place a new order"
      description: "Place a new order for the authenticated user."
      parameters:
        - in: "body"
          name: "body"
          description: "Order details"
          required: true
          schema:
            $ref: "#/definitions/Order"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        201:
          description: "Order created successfully"
        400:
          description: "Invalid input"

  /orders/{order_id}:
    get:
      tags:
        - "Order"
      summary: "Get order details"
      description: "Retrieve details of an order by its ID."
      parameters:
        - in: "path"
          name: "order_id"
          required: true
          type: "integer"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Order details"
          schema:
            $ref: "#/definitions/Order"
        404:
          description: "Order not found"

    put:
      tags:
        - "Order"
      summary: "Update an order"
      description: "Update details of an existing order by its ID."
      parameters:
        - in: "path"
          name: "order_id"
          required: true
          type: "integer"
        - in: "body"
          name: "body"
          description: "Updated order details"
          required: true
          schema:
            $ref: "#/definitions/Order"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Order updated successfully"
        404:
          description: "Order not found"

    delete:
      tags:
        - "Order"
      summary: "Delete an order"
      description: "Delete an order by its ID."
      parameters:
        - in: "path"
          name: "order_id"
          required: true
          type: "integer"
      security:
        - Bearer: []  # Require Bearer token for this endpoint
      responses:
        200:
          description: "Order deleted successfully"
        404:
          description: "Order not found"

definitions:
  Product:
    type: "object"
    required:
      - name
      - price
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      description:
        type: "string"
      price:
        type: "number"
        format: "float"
      stock:
        type: "integer"
      created_at:
        type: "string"
        format: "date-time"

  Order:
    type: "object"
    required:
      - user_id
      - total_price
    properties:
      id:
        type: "integer"
      user_id:
        type: "integer"
      total_price:
        type: "number"
        format: "float"
      created_at:
        type: "string"
        format: "date-time"
      status:
        type: "string"