"""order update

Revision ID: 8d8871bbe084
Revises: e37583332e6f
Create Date: 2024-08-23 21:02:43.094000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8871bbe084'
down_revision = 'e37583332e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_item', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'product', ['order_item'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_item')

    # ### end Alembic commands ###
